# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/racimrgh/Windows-SSD/Users/racim/OneDrive/Documents/L3-CERGY/S2/OS/projets/OS-memory-simulation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/racimrgh/Windows-SSD/Users/racim/OneDrive/Documents/L3-CERGY/S2/OS/projets/OS-memory-simulation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/racimrgh/Windows-SSD/Users/racim/OneDrive/Documents/L3-CERGY/S2/OS/projets/OS-memory-simulation/CMakeFiles /media/racimrgh/Windows-SSD/Users/racim/OneDrive/Documents/L3-CERGY/S2/OS/projets/OS-memory-simulation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/racimrgh/Windows-SSD/Users/racim/OneDrive/Documents/L3-CERGY/S2/OS/projets/OS-memory-simulation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Memoire

# Build rule for target.
Memoire: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Memoire
.PHONY : Memoire

# fast build rule for target.
Memoire/fast:
	$(MAKE) -f CMakeFiles/Memoire.dir/build.make CMakeFiles/Memoire.dir/build
.PHONY : Memoire/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) -f CMakeFiles/docs.dir/build.make CMakeFiles/docs.dir/build
.PHONY : docs/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/Memoire.dir/build.make CMakeFiles/Memoire.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/Memoire.dir/build.make CMakeFiles/Memoire.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/Memoire.dir/build.make CMakeFiles/Memoire.dir/main.c.s
.PHONY : main.c.s

src/memory.o: src/memory.c.o

.PHONY : src/memory.o

# target to build an object file
src/memory.c.o:
	$(MAKE) -f CMakeFiles/Memoire.dir/build.make CMakeFiles/Memoire.dir/src/memory.c.o
.PHONY : src/memory.c.o

src/memory.i: src/memory.c.i

.PHONY : src/memory.i

# target to preprocess a source file
src/memory.c.i:
	$(MAKE) -f CMakeFiles/Memoire.dir/build.make CMakeFiles/Memoire.dir/src/memory.c.i
.PHONY : src/memory.c.i

src/memory.s: src/memory.c.s

.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.c.s:
	$(MAKE) -f CMakeFiles/Memoire.dir/build.make CMakeFiles/Memoire.dir/src/memory.c.s
.PHONY : src/memory.c.s

src/menu.o: src/menu.c.o

.PHONY : src/menu.o

# target to build an object file
src/menu.c.o:
	$(MAKE) -f CMakeFiles/Memoire.dir/build.make CMakeFiles/Memoire.dir/src/menu.c.o
.PHONY : src/menu.c.o

src/menu.i: src/menu.c.i

.PHONY : src/menu.i

# target to preprocess a source file
src/menu.c.i:
	$(MAKE) -f CMakeFiles/Memoire.dir/build.make CMakeFiles/Memoire.dir/src/menu.c.i
.PHONY : src/menu.c.i

src/menu.s: src/menu.c.s

.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.c.s:
	$(MAKE) -f CMakeFiles/Memoire.dir/build.make CMakeFiles/Memoire.dir/src/menu.c.s
.PHONY : src/menu.c.s

src/process.o: src/process.c.o

.PHONY : src/process.o

# target to build an object file
src/process.c.o:
	$(MAKE) -f CMakeFiles/Memoire.dir/build.make CMakeFiles/Memoire.dir/src/process.c.o
.PHONY : src/process.c.o

src/process.i: src/process.c.i

.PHONY : src/process.i

# target to preprocess a source file
src/process.c.i:
	$(MAKE) -f CMakeFiles/Memoire.dir/build.make CMakeFiles/Memoire.dir/src/process.c.i
.PHONY : src/process.c.i

src/process.s: src/process.c.s

.PHONY : src/process.s

# target to generate assembly for a file
src/process.c.s:
	$(MAKE) -f CMakeFiles/Memoire.dir/build.make CMakeFiles/Memoire.dir/src/process.c.s
.PHONY : src/process.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Memoire"
	@echo "... docs"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/process.o"
	@echo "... src/process.i"
	@echo "... src/process.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

